### ISSUE TITLE
Setup project with app template

### ISSUE THREAD

**Issue by caseycesari** [azavea/iow-boundary-tool#1]
Use https://github.com/azavea/civic-apps-app-template to bootstrap the repo.

Instructions are available at https://github.com/azavea/civic-apps-app-template/blob/develop/PROJECT_CHECKLIST.md

In the process, update any libraries that may be out-of-date.

**Comment by nanotubing** [comment]
I've got the base repo set up from the template. Next I'm going to update older libraries, and update the docker config to reflect the changes necessary for development on apple silicon
