### ISSUE TITLE
Support Opacity for Reference Images

### ISSUE THREAD

**Issue by rajadain** [azavea/iow-boundary-tool#126]
## Overview

At some point, we may allow the user to set an opacity value for reference images, beyond the one setting available in L.DistortableImage. In preparation, add an integer column to the ReferenceImage model to store the opacity value. It should be limited to values between 0 and 100. It should default to 100. The reference image update endpoint should allow setting this value, in addition to the distortion parameters.

**Comment by jacobtylerwalls** [comment]
Should we mark as closed by #144 or alter the card description?

**Comment by rajadain** [comment]
Yes we should!
