### ISSUE TITLE
Draw Page: Add, Update Reference Images

### ISSUE THREAD

**Issue by rajadain** [azavea/iow-boundary-tool#131]
## Overview

When a reference image is added in the Draw Page, it should be uploaded to the back-end.

Whenever a reference image is manipulated (distorted, made visible or not, or have its opacity adjusted), that should be updated in the back-end.

**Comment by jacobtylerwalls** [comment]
@rajadain Is this blocked by #81?

**Comment by rajadain** [comment]
They can be done in either order. If this is done first, then we only do metadata, and add file uploads as part of #81. If that is done first, then #81 becomes more back-end focused, and all front-end implementation including file uploads is done here.
