### ISSUE TITLE
Automatically determine utility at utillity specific URLs

### ISSUE THREAD

**Issue by mstone121** [azavea/iow-boundary-tool#184]
## Overview

Going straight to a utility specific URL (e.g. `/submissions/4` or `/draw/4`) still shows the utility selector. This can be annoying and potentially confusing. If a user selects a utility not related to that of the URL's item, then the user will still see the URL item, but will have a different utility selected.

### Describe the solution you'd like

Automatically set the utility when the user visits one of these URLs

We should wrap all of the utility specific routes in a component which defers rendering of its children until the utility is set. This would probably be easier to do if we moved the draw page "into" submissions: `/submissions/4/draw`.

**Comment by rajadain** [comment]
This would pair well with #172

**Comment by mstone121** [comment]
> which cannot be done with Hooks

It should be possible with RTK query: https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching.

**Comment by rajadain** [comment]
Shares points with #216
