### ISSUE TITLE
Release 0.9.3

### ISSUE THREAD

**Issue by stephwall** [azavea/iow-boundary-tool#235]
- [x] Start a new release branch:
    ```bash
    git flow release start 0.9.3
    ```
- [x] Rotate `CHANGELOG.md` (following [Keep a Changelog](https://keepachangelog.com/) principles)
- [x] Ensure outstanding changes are committed:
    ```bash
    git status # Is the git staging area clean?
    git add CHANGELOG.md
    git commit -m "0.9.3"
    ```
- [x] Publish the release branch:
    ```bash
    git flow release publish 0.9.3
    ```
- [x] Test the release branch [on staging](https://staging.iow.azavea.com/)
- [x] Start a new [release pipeline job](https://github.com/azavea/iow-boundary-tool/actions/workflows/release.yml) with the SHA (see command below) of `release/0.9.3` that was tested on staging
    ```bash
    git rev-parse --short HEAD
    ```
- [x] Run migrations, if applicable (see the `showmigrations` release pipeline stage):
    ```bash
    ./scripts/manage ecsmanage -e production migrate
    ```
- [x] If necessary, [publish any new tiles](https://github.com/azavea/iow-boundary-tool/blob/develop/data/README.md#deployment)
- [x] Finish and publish the release branch:
    - When prompted, keep default commit messages
    - Use `0.9.3` as the tag message
    ```bash
    git flow release finish -p 0.9.3
    ```

**Comment by rajadain** [comment]
Production deploy is complete. Confirmed that I can see the new national municipal boundary in production:

![image](https://github.com/azavea/iow-boundary-tool/assets/1430060/76472b9d-6084-4ec3-abaf-72dcdff1ec4c)
