### ISSUE TITLE
Add Municipal Boundaries Layer

### ISSUE THREAD

**Issue by rajadain** [azavea/iow-boundary-tool#34]
## Overview

- [ ] Find out which Municipal Boundaries layer we're using
- [ ] Decide if it can be queried from a remote source or if it needs to be ingested and tiled
  - [ ] If needed, ingest it
  - [ ] Tile it
- [ ] Add to map, wire up to Municipal Boundaries button under Basemap Layers

**Comment by caseycesari** [comment]
Possible data source https://linc.osbm.nc.gov/explore/dataset/municipalities-2020/information/?disjunctive.name20&location=6,36.96224,-74.88288&basemap=jawg.streets&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6Im11bmljaXBhbGl0aWVzLTIwMjAiLCJvcHRpb25zIjp7ImRpc2p1bmN0aXZlLm5hbWUyMCI6dHJ1ZSwiYmFzZW1hcCI6Imphd2cuc3RyZWV0cyIsImxvY2F0aW9uIjoiNywzNS4yMDYzLC03OS44MDM3NCJ9fSwiY2hhcnRzIjpbeyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJBVkciLCJ5QXhpcyI6ImxhbmRhcmVhIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiIzQ4N0FBOCJ9XSwieEF4aXMiOiJ5ZWFyX2luY29ycG9yYXRlZCIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIn1dLCJkaXNwbGF5TGVnZW5kIjp0cnVlLCJhbGlnbk1vbnRoIjp0cnVlfQ%3D%3D
