### ISSUE TITLE
Reuse Map Component Between Routes

### ISSUE THREAD

**Issue by rajadain** [azavea/iow-boundary-tool#45]
## Overview

Currently as the user moves between `/welcome` and `/draw` routes, the Map component is reloaded. This is apparent through the refetching of tiles, and likely has non-visible impacts as well (on CPU / network usage):

![2022-08-24 16 12 11](https://user-images.githubusercontent.com/1430060/186514743-67b6b4a7-293c-40c9-877d-ed8098b80698.gif)

The Map, being one of the heaviest and most complex components of the app, should not be casually re-rendered.

Originally discovered in: https://github.com/azavea/iow-boundary-tool/pull/43#issuecomment-1226242407

### Describe the solution you'd like

Make it so that the Map is initialized once for the app, and is reused throughout.

**Comment by mstone121** [comment]
Added in https://github.com/azavea/iow-boundary-tool/pull/57.
