### ISSUE TITLE
Update map layer styles

### ISSUE THREAD

**Issue by caseycesari** [azavea/iow-boundary-tool#49]
Consult with design on the following changes:

1. Add name labels. There is a field (`name20`) that can be used.
~~2. Modify the style of the boundaries so that it's easier to see what is contained within a municipality, and what is outside of one. I think a somewhat transparent fill color could help, as well as making the boundary line less dashed.~~ Already done in #48
~~3. Change the polygon layer to be more visible when it is displayed over the satellite basemap layer.~~ Deferred to #56

**Comment by rajadain** [comment]
> **Layer styles**: [figma.com/file/tJPZ0lkT5C3SAyS2g2R1aA/IoW---Boundary-Sync-Tool?node-id=498%3A14829](https://www.figma.com/file/tJPZ0lkT5C3SAyS2g2R1aA/IoW---Boundary-Sync-Tool?node-id=498%3A14829)
Style updates to the municipal boundary, polygon edge, polygon face, and vertices.

~ @gatesgodin https://github.com/azavea/iow-boundary-tool/pull/48#issuecomment-1232036069
