### ISSUE TITLE
Update `DEFAULT_FROM_EMAIL` before deployment

### ISSUE THREAD

**Issue by jacobtylerwalls** [azavea/iow-boundary-tool#80]
Need a from email for password reset before deployment. Maybe this is in a checklist somewhere, but can't hurt to document.

https://github.com/azavea/iow-boundary-tool/blob/cbfc7806a4a261e1a69945da617ee9e6a6096f7a/src/django/iow/settings.py#L274

**Comment by rajadain** [comment]
Covered by #119.
