### ISSUE TITLE
Wire up Draw Page to Save Data

### ISSUE THREAD

**Issue by rajadain** [azavea/iow-boundary-tool#88]
## Overview

The Draw Page allows the Contributor to add the following pieces of data:

- Reference Images
  - File name
  - File data
  - Order in which it was added
  - Whether it is visible or not
  - Distortion
- Polygon
  - Shape
  - Optional uploaded shapefile
    - File name
    - File data
    - Whether it was edited after upload

Check with @gatesgodin whether this information should be persisted on every change, or only when the user clicks "Save and back" or "Review and submit".

Once clarified, implement the saving of this information to the relevant models on the back-end.

**Comment by jacobtylerwalls** [comment]
Checked w/ Gates, we want to save on every change.
